name: aukf
channels: [conda-forge]
dependencies:
  - python=3.11          # CI will overwrite per-matrix
  - numpy>=1.23
  - pandas>=1.5
  - scipy>=1.10
  - matplotlib>=3.7
  - seaborn>=0.12
  - statsmodels>=0.13

  # I/O & perf
  - pyarrow>=11
  - fastparquet
  - numba
  - cython

  # Jupyter
  - jupyterlab=4
  - ipykernel

  # Orekit stack
  - orekit=12.1.2
  - jpype1=1.5
  - openjdk=8

  # dev / test (lighter than pip extras)
  - pytest
  - pytest-cov
  - black
  - flake8
  - pre-commit

  - pip                         # still allow pip extras
