name: satellite-aukf
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9
  
  # Core scientific computing
  - numpy=1.23.*
  - pandas=1.5.*
  - scipy=1.10.*
  
  # Visualization
  - matplotlib=3.7.*
  - seaborn=0.12.*
  
  # Jupyter environment
  - jupyter=1.0.*
  - ipykernel=6.22.*
  - notebook=6.5.*
  - jupyterlab=3.6.*
  
  # Statistical analysis
  - statsmodels=0.13.*
  
  # Testing
  - pytest=7.3.*
  - pytest-cov=4.0.*
  
  # Development tools
  - black=23.3.*
  - flake8=6.0.*
  - mypy=1.2.*
  
  # Data handling
  - pyarrow=11.0.*
  - pytables=3.8.*
  
  # Performance
  - numba=0.57.*
  - cython=0.29.*
  
  # Java for Orekit
  - openjdk=11.*
  
  # Pip dependencies (Orekit not available in conda)
  - pip
  - pip:
    - orekit>=11.3
    - colorlog>=6.7.0
    - python-dotenv>=1.0.0
    - typing-extensions>=4.5.0